language: node_js
node_js:
  - "node"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script: gulp sass:delivery

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
